/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorsIdRouteImport } from './routes/mentors_.$id'
import { Route as MenteesIdRouteImport } from './routes/mentees.$id'
import { Route as DashboardMentorRouteImport } from './routes/dashboard.mentor'
import { Route as DashboardMenteeRouteImport } from './routes/dashboard.mentee'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as BookMentorIdRouteImport } from './routes/book.$mentorId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIdRoute = MentorsIdRouteImport.update({
  id: '/mentors_/$id',
  path: '/mentors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MenteesIdRoute = MenteesIdRouteImport.update({
  id: '/mentees/$id',
  path: '/mentees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/dashboard/mentor',
  path: '/dashboard/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMenteeRoute = DashboardMenteeRouteImport.update({
  id: '/dashboard/mentee',
  path: '/dashboard/mentee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMentorIdRoute = BookMentorIdRouteImport.update({
  id: '/book/$mentorId',
  path: '/book/$mentorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/book/$mentorId': typeof BookMentorIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentee': typeof DashboardMenteeRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/mentees/$id': typeof MenteesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/book/$mentorId': typeof BookMentorIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentee': typeof DashboardMenteeRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/mentees/$id': typeof MenteesIdRoute
  '/mentors/$id': typeof MentorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/book/$mentorId': typeof BookMentorIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/mentee': typeof DashboardMenteeRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/mentees/$id': typeof MenteesIdRoute
  '/mentors_/$id': typeof MentorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/forgot-password'
    | '/login'
    | '/mentors'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/book/$mentorId'
    | '/dashboard/admin'
    | '/dashboard/mentee'
    | '/dashboard/mentor'
    | '/mentees/$id'
    | '/mentors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/forgot-password'
    | '/login'
    | '/mentors'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/book/$mentorId'
    | '/dashboard/admin'
    | '/dashboard/mentee'
    | '/dashboard/mentor'
    | '/mentees/$id'
    | '/mentors/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/forgot-password'
    | '/login'
    | '/mentors'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/book/$mentorId'
    | '/dashboard/admin'
    | '/dashboard/mentee'
    | '/dashboard/mentor'
    | '/mentees/$id'
    | '/mentors_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  BookMentorIdRoute: typeof BookMentorIdRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardMenteeRoute: typeof DashboardMenteeRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  MenteesIdRoute: typeof MenteesIdRoute
  MentorsIdRoute: typeof MentorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors_/$id': {
      id: '/mentors_/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof MentorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentees/$id': {
      id: '/mentees/$id'
      path: '/mentees/$id'
      fullPath: '/mentees/$id'
      preLoaderRoute: typeof MenteesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/dashboard/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mentee': {
      id: '/dashboard/mentee'
      path: '/dashboard/mentee'
      fullPath: '/dashboard/mentee'
      preLoaderRoute: typeof DashboardMenteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$mentorId': {
      id: '/book/$mentorId'
      path: '/book/$mentorId'
      fullPath: '/book/$mentorId'
      preLoaderRoute: typeof BookMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  BookMentorIdRoute: BookMentorIdRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardMenteeRoute: DashboardMenteeRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  MenteesIdRoute: MenteesIdRoute,
  MentorsIdRoute: MentorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
